Vagrant.configure ("2") do |config|
  # Create a centos 7 box
  config.vm.box = "centos/7"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machine on the same network, but cannot be accessed (through
  # this network interface) by any external networks.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # update the server
  config.vm.provision "shell", inline: "yum update"

  config.vm.hostname = "hitesh-test"
  config.vm.provision "shell", inline: "yum install -y net-tools.x86_64"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
